image: node:9.8.0

stages:
  - test

cache:
  paths:
  - node_modules/

# test
test:
  stage: test
  script:
    - npm install
    - npm test
lint:
  stage: test
  script:
    - npm install
    - npm run lint
flow:
  stage: test
  script:
    - npm install
    - npm run flow

#pack:
#  stage: deploy
#  script:
#    - npm install
#    - npm pack
#  artifacts:
#    paths:
#    - ./*.tgz